package mike.sokoryansky.MathUtils

import org.scalatest.FunSuite

class TestPythagorean extends FunSuite {
  test("rightTriangles returns all integer-sides right triangles for a given perimeter") {
    assert(Pythagorean.pythagoreanTriple(-2) === List())
    assert(Pythagorean.pythagoreanTriple(0) === List())
    assert(Pythagorean.pythagoreanTriple(1) === List())
    assert(Pythagorean.pythagoreanTriple(2) === List())
    assert(Pythagorean.pythagoreanTriple(3) === List())
    assert(Pythagorean.pythagoreanTriple(4) === List())
    assert(Pythagorean.pythagoreanTriple(5) === List())
    assert(Pythagorean.pythagoreanTriple(6) === List())
    assert(Pythagorean.pythagoreanTriple(7) === List())
    assert(Pythagorean.pythagoreanTriple(8) === List())
    assert(Pythagorean.pythagoreanTriple(9) === List())
    assert(Pythagorean.pythagoreanTriple(10) === List())
    assert(Pythagorean.pythagoreanTriple(11) === List())
    assert(Pythagorean.pythagoreanTriple(12) === List((3, 4, 5)))
    assert(Pythagorean.pythagoreanTriple(13) === List())
    assert(Pythagorean.pythagoreanTriple(14) === List())
    assert(Pythagorean.pythagoreanTriple(15) === List())
    assert(Pythagorean.pythagoreanTriple(16) === List())
    assert(Pythagorean.pythagoreanTriple(17) === List())
    assert(Pythagorean.pythagoreanTriple(18) === List())
    assert(Pythagorean.pythagoreanTriple(19) === List())
    assert(Pythagorean.pythagoreanTriple(20) === List())
    assert(Pythagorean.pythagoreanTriple(21) === List())
    assert(Pythagorean.pythagoreanTriple(22) === List())
    assert(Pythagorean.pythagoreanTriple(23) === List())
    assert(Pythagorean.pythagoreanTriple(24) === List((6, 8, 10)))
    assert(Pythagorean.pythagoreanTriple(25) === List())
    assert(Pythagorean.pythagoreanTriple(26) === List())
    assert(Pythagorean.pythagoreanTriple(27) === List())
    assert(Pythagorean.pythagoreanTriple(28) === List())
    assert(Pythagorean.pythagoreanTriple(29) === List())
    assert(Pythagorean.pythagoreanTriple(30) === List((5, 12, 13)))
    assert(Pythagorean.pythagoreanTriple(31) === List())
    assert(Pythagorean.pythagoreanTriple(32) === List())
    assert(Pythagorean.pythagoreanTriple(33) === List())
    assert(Pythagorean.pythagoreanTriple(34) === List())
    assert(Pythagorean.pythagoreanTriple(35) === List())
    assert(Pythagorean.pythagoreanTriple(36) === List((9, 12, 15)))
    assert(Pythagorean.pythagoreanTriple(37) === List())
    assert(Pythagorean.pythagoreanTriple(38) === List())
    assert(Pythagorean.pythagoreanTriple(39) === List())
    assert(Pythagorean.pythagoreanTriple(40) === List((8, 15, 17)))
    assert(Pythagorean.pythagoreanTriple(41) === List())
    assert(Pythagorean.pythagoreanTriple(42) === List())
    assert(Pythagorean.pythagoreanTriple(43) === List())
    assert(Pythagorean.pythagoreanTriple(44) === List())
    assert(Pythagorean.pythagoreanTriple(45) === List())
    assert(Pythagorean.pythagoreanTriple(46) === List())
    assert(Pythagorean.pythagoreanTriple(47) === List())
    assert(Pythagorean.pythagoreanTriple(48) === List((12, 16, 20)))
    assert(Pythagorean.pythagoreanTriple(50) === List())
    assert(Pythagorean.pythagoreanTriple(51) === List())
    assert(Pythagorean.pythagoreanTriple(52) === List())
    assert(Pythagorean.pythagoreanTriple(53) === List())
    assert(Pythagorean.pythagoreanTriple(54) === List())
    assert(Pythagorean.pythagoreanTriple(55) === List())
    assert(Pythagorean.pythagoreanTriple(56) === List((7, 24, 25)))
    assert(Pythagorean.pythagoreanTriple(60) === List((10, 24, 26), (15, 20, 25)))
    assert(Pythagorean.pythagoreanTriple(120) === List((20,48,52), (24,45,51), (30,40,50)))
  }
}
